### PR TITLE
Add a readability check to Vale linter

### PR DESCRIPTION
**Pull request by agentolivia**
- Create readability.yml to /styles directory.

This tutorial should produce a warning:

- /configuration_management/how-override-configuration.md

This tutorial should pass:

- /dr-projects/movie/movieproject07.md

Readability scores from 2019 can be found here:
https://docs.google.com/spreadsheets/d/1F_OMp71cQnEr6VZ_G4rnlAqB0QL7wGdhpe2W1Hkc6tw/edit#gid=0

### CODE REVIEW

**Comment by agentolivia** [comment]
@eojthebrave I'm not sure exactly how I would test this on my local. Help?

**Comment by eojthebrave** [comment]
I think the easiest way is probably to run the updated code by calling it directly instead of using npm. Though you could also try `npm link`.

Assuming the directory structure:

```txt
drupalizeme_tutorials/
osiolabs-copyeditor/
```

Try:

```
cd drupalizeme_tutorials/
vale --config='../osiolabs-copyeditor/.vale.ini' tutorials/entityapi/entity-query.md
```

**Comment by eojthebrave** [comment]
Ooh. Or even easier. Just run it on the test.md file in this repo (which you can edit to add whatever text you want to test).

Just run `vale test.md` in the osiolabs-copyeditor directory

**Comment by eojthebrave** [comment]
I found an error in the replacements.yml file that was making it impossible to test this out. But, with that fixed this is working for me locally.

@agentolivia I'll leave this open so you can test it out locally too (you'll need to pull my change in). But feel free to merge this when you're happy with it.

I think we probably need to run `npm update osiolabs-copyeditor` in the dme content repo after that's done before it'll be present in the d.me CI jobs.

**Comment by agentolivia** [comment]
This is working as expected. Woot!

tutorials — -fish — 111×56 2021-04-28 19-46-14

I'll go ahead and merge this in. Thanks @eojthebrave!

**Pull request merged**
